### ISSUE TITLE
Make YAML anchors possible in the config

### ISSUE THREAD

**Issue by mattmb** [ministryofjustice/bootstrap-cfn#102]
i.e. make this work: 

``` yaml
dev: &DEV
  ec2:
    auto_scaling:
      desired: 2
      max: 3
      min: 1
    tags:
      Role: docker
      Apps: crimebillingonline
      Env: dev
    parameters:
      KeyName: default
      InstanceType: m3.large
    block_devices:
      - DeviceName: /dev/sda1
        VolumeSize: 10
      - DeviceName: /dev/sdg
        VolumeSize: 10
    security_groups:
      MyBaseSG:
        - …
      WebServer:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId:
            Ref: DefaultSGdev
      MySaltSG:
        - IpProtocol: tcp
          FromPort: 4505
          ToPort: 4506
          SourceSecurityGroupId:
            Ref: MyBaseSG
  elb:
    - name: dev
      hosted_zone: crimebillingonline.dsd.io.
      scheme: internet-facing
      listeners:
        - LoadBalancerPort: 80
          InstancePort: 80
          Protocol: TCP
  s3:
    static-bucket-name: cbo-dev-assets


demo:
  # Demo is like dev, but with these changes
  <<: *DEV
  ec2:
    tags:
      Env: demo
    security_groups:
      WebServer:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId:
            Ref: DefaultSGdemo
  elb:
    - name: demo
      hosted_zone: crimebillingonline.dsd.io.
      scheme: internet-facing
      listeners:
        - LoadBalancerPort: 80
          InstancePort: 80
          Protocol: TCP
  s3:
    static-bucket-name: cbo-demo-assets
  rds:
    db-name: cbo-demo

```

Not sure if this is easy or not but seems like it would be cleaner.

**Comment by ashb** [comment]
One possible option might be something like this:

``` yaml
dev: &DEV
  ec2:
    auto_scaling:
      desired: 1
      max: 1
      min: 1

demo:
  __merge_with__: *DEV
  ec2:
    auto_scaling:
      desired: 10
      max: 10
      min: 1
```

and then our python code looks for `__merge_with__` and does the deep merge for us.

**Comment by SteveMarshall** [comment]
Another possibility (though one I'm not sure I'm entirely sold on) might be:

``` yaml
dev: &dev
  ec2: &dev_ec2
    auto_scaling: &dev_ec2_auto_scaling
      desired: 1
      max: 1
      min: 1

demo:
  <<: *dev
  ec2:
    <<: *dev_ec2
    auto_scaling:
      <<: *dev_ec2_auto_scaling
      desired: 10
      max: 10
```

It's a bit more verbose, but allows (I think?) more fine grained control and a way to completely override a given block to null? It also requires absolutely no development on our part, aside from specifying anchors _everywhere_.

**Comment by SteveMarshall** [comment]
Another wrinkle with my anchor-all-the-things idea is sequences. There's apparently no way to add to/merge a sequence, so this is invalid:

``` yaml
dev: &dev
  ec2: &dev_ec2
    block_devices: &dev_ec2_block_devices
      - DeviceName: /dev/sda1
        VolumeSize: 10
      - DeviceName: /dev/sdf
        VolumeSize: 10

live:
  ec2:
    block_devices:
      *dev_ec2_block_devices
      - DeviceName: /dev/sda2
        VolumeSize: 10
```

… as is using `<<:` to attempt to inject the sequence. It does, however, work if you don't try to append the `/dev/sda2` sequence item (so that's how you re-add an anchored sequence in full). One thing that _might_ be interesting is this:

``` yaml
# […]

live:
  ec2:
    block_devices:
      - *dev_ec2_block_devices
      - DeviceName: /dev/sda2
        VolumeSize: 10
```

… which results in `block_devices` containing a sequence with two items: a sequence containing all the items from `dev_ec2_block_devices`, and the `/dev/sda2` item… So maybe some liberal flattening where the first item is a sequence could be in order? But if we're going to do that, why not just write our own deep-merge? And what happens if you _intend_ for the first item in a sequence to be a sequence?

**Comment by ashb** [comment]
I think the chaging a list thing falls down either way (anchors or **merge**).

The 'lots of anchors' approach does work but is a little bit verbose for my tastes. I don't feel that strongly against it though.

**Comment by SteveMarshall** [comment]
I thought I'd take @mattmb's initial example and refactor to the anchor-all-the-things. It comes out like this:

``` yaml
dev: &dev
  ec2: &dev_ec2
    auto_scaling:
      desired: 2
      max: 3
      min: 1
    tags: &dev_ec2_tags
      Role: docker
      Apps: crimebillingonline
      Env: dev
    parameters:
      KeyName: default
      InstanceType: m3.large
    block_devices:
      - DeviceName: /dev/sda1
        VolumeSize: 10
      - DeviceName: /dev/sdg
        VolumeSize: 10
    security_groups: &dev_ec2_tags_security_groups
      MyBaseSG:
        - …
      WebServer:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId:
            Ref: DefaultSGdev
      MySaltSG:
        - IpProtocol: tcp
          FromPort: 4505
          ToPort: 4506
          SourceSecurityGroupId:
            Ref: MyBaseSG
  elb:
    - name: dev
      hosted_zone: crimebillingonline.dsd.io.
      scheme: internet-facing
      listeners:
        - LoadBalancerPort: 80
          InstancePort: 80
          Protocol: TCP
  s3:
    static-bucket-name: cbo-dev-assets


demo:
  <<: *dev
  ec2:
    <<: *dev_ec2
    tags:
      <<: *dev_ec2_tags
      Env: demo
    security_groups:
      <<: *dev_ec2_tags_security_groups
      WebServer:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId:
            Ref: DefaultSGdemo
  elb:
    - name: demo
      hosted_zone: crimebillingonline.dsd.io.
      scheme: internet-facing
      listeners:
        - LoadBalancerPort: 80
          InstancePort: 80
          Protocol: TCP
  s3:
    static-bucket-name: cbo-demo-assets
  rds:
    db-name: cbo-demo
```
