### ISSUE TITLE
Pin down the Cipher policy for ELB listener on port 443

### ISSUE THREAD

**Issue by bennythejudge** [ministryofjustice/bootstrap-cfn#120]
This refers to an [existing ticket](https://github.com/ministryofjustice/platforms-team/issues/8) on Waffle.
After investigations, the current Amazon default policy ("PolicyName": "ELBSecurityPolicy-2015-05") is acceptable and works with IE7.
Pin down this policy in cloudformation via troposphere in config.py.
More information can be found [here](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/elb-security-policy-table.html)

**Comment by bennythejudge** [comment]
1) Amazon security policy for ELB Listener can be selected via YAML:

```
  elb:
    - name: opstest1
      hosted_zone: advocatedefencepayments.dsd.io.
      scheme: internet-facing
      certificate_name: opstest1-cert
      listeners:
        - LoadBalancerPort: 80
          InstancePort: 80
          Protocol: HTTP
        - LoadBalancerPort: 443
          InstancePort: 80
          Protocol: HTTPS
          PolicyNames:
            - ELBSecurityPolicy-2015-05
```

I have tested against current version of bootstrap-cfn (0.5.0) and it works. 

2) the above works only with current policy (2015-05), while it doesn't work with previous (older) versions.
Trying to use 2015-03 results in cfn_create error with the following message:

```
There is no policy with name ELBSecurityPolicy-2015-03 for load balancer ELB-opstest1
```

3) testing if [this](https://forums.aws.amazon.com/thread.jspa?messageID=595522#595522) is a solution.
