### ISSUE TITLE
Elastic IPs

### ISSUE THREAD

**Issue by mattmb** [ministryofjustice/bootstrap-cfn#155]
Some projects need to use a specific IP address and so we have used elastic IPs.

Because the instances are in autoscaling groups if they come and go they will get a new IP each time and we have to manually assign an elastic IP.

What would be nice is to specify a list of elastic IPs in the cloudformation template and for the instances to automatically "get" one of these IPs if it can.

I'm thinking:

```
  ec2:
    auto_scaling:
      desired: 1
      max: 3
      min: 0
    elastic_ips:
      - 54.1.1.1
      - 54.1.1.2
      - 54.1.1.3
```

And then a boto script in the userdata that somehow tries to associate each of these if they are available.
