### ISSUE TITLE
Add multiple s3 buckets

### ISSUE THREAD

**Issue by sevenmachines** [ministryofjustice/bootstrap-cfn#157]
Add the ability to add a 'groups' tag to the s3 section and set an arbitrary number of custom s3 buckets for the stack.

```
s3:
  - groups
       my-new-bucket:
           policy: some-policy.json
      another-bucket-name: {}
```
