### ISSUE TITLE
Allow configuring EC2 volume type

### ISSUE THREAD

**Issue by sevenmachines** [ministryofjustice/bootstrap-cfn#160]
At the moment we default to EBSBlockDevice, we need to be able to allow SSD 

for example:

```
  prod:
    master_zone: domain.io
    ec2:
      block_devices:
        - DeviceName: /dev/sda1
          VolumeSize: 10
       - DeviceName: /dev/sdf
          VolumeType: gp2
          VolumeSize: 20
        - DeviceName: /dev/sdg
          VolumeType: io1
          Iops: 1200
          VolumeSize: 20
```
