### ISSUE TITLE
elbs with same name but different hosted zones fail

### ISSUE THREAD

**Issue by ltsampros** [ministryofjustice/bootstrap-cfn#278]
Example ELB config:

```
  elb:
    - name: hostname
      hosted_zone: zone0.example.com
      scheme: internet-facing
      certificate_name: mtp-cert-prod
      health_check: *base_elb_health_check
      listeners: *base_elb_listeners
    - name: hostname
      hosted_zone: zone1.example.com.
      scheme: internet-facing
```

while the above configuration is a valid configuration, we get a failure dor a duplicate logical ID in the template.

Root issue is that we construct the ELB logical id in the template it elf which is just the `name' key from the config with some forbidden characters removed.

The traceback looks like this:
```po
Traceback (most recent call last):
  File "/Users/leonidastsampros/.virtualenvs/test-deploy/lib/python2.7/site-packages/fabric/main.py", line 757, in main
    *args, **kwargs
  File "/Users/leonidastsampros/.virtualenvs/test-deploy/lib/python2.7/site-packages/fabric/tasks.py", line 426, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/Users/leonidastsampros/.virtualenvs/test-deploy/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/leonidastsampros/.virtualenvs/test-deploy/lib/python2.7/site-packages/bootstrap_salt/fab_tasks.py", line 207, in cfn_update
    bcfn_update(*args, **kwargs)
  File "/Users/leonidastsampros/.virtualenvs/test-deploy/lib/python2.7/site-packages/fabric/tasks.py", line 170, in __call__
    return self.run(*args, **kwargs)
  File "/Users/leonidastsampros/.virtualenvs/test-deploy/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/leonidastsampros/.virtualenvs/test-deploy/lib/python2.7/site-packages/bootstrap_cfn/fab_tasks.py", line 730, in cfn_update
    new_body = cfn_config.process_update(body)
  File "/Users/leonidastsampros/.virtualenvs/test-deploy/lib/python2.7/site-packages/bootstrap_cfn/config.py", line 186, in process_update
    self.elb(template)
  File "/Users/leonidastsampros/.virtualenvs/test-deploy/lib/python2.7/site-packages/bootstrap_cfn/config.py", line 998, in elb
    Value=GetAtt(load_balancer, "DNSName")
  File "/Users/leonidastsampros/.virtualenvs/test-deploy/lib/python2.7/site-packages/troposphere/__init__.py", line 516, in add_output
    return self._update(self.outputs, output)
  File "/Users/leonidastsampros/.virtualenvs/test-deploy/lib/python2.7/site-packages/troposphere/__init__.py", line 511, in _update
    self.handle_duplicate_key(values.title)
  File "/Users/leonidastsampros/.virtualenvs/test-deploy/lib/python2.7/site-packages/troposphere/__init__.py", line 501, in handle_duplicate_key
    raise ValueError('duplicate key "%s" detected' % key)
ValueError: duplicate key "ELBhostmoney" detected```
